### ISSUE TITLE
Tinkers' construct EFLN doesn't break blocks with this mod installed

### ISSUE THREAD

**Issue by TeetoKaziim** [maruohon/environmentalcreepers#2]
Minecraft Version: 1.10.2
Environmental Creepers Version: 1.11.2-1.2.1
Tinkers Construct Version: 1.10.2-2.6.5
Mantle Version: 1.10.2-1.1.5
Forge Version: 12.18.3.2316

Default configs on all mods.

So, first off, love this mod, does everything I want, and only one thing I don't want, and that thing is:

Tinkers' construct includes a special throwable explosive item called the EFLN, whose primary property is that it leaves behind 100% of the blocks it breaks. But with environmental creepers installed, this explosive still makes its pretty graphics, but breaks no blocks, as if they were bedrock or something unbreakable.

Seriously though, love this, would love to keep using it. Never again will a creeper sneak up on me while I'm filling up a drum, blow up, knock me into the lava, and annihilate my drum. Now it'll do everything but that last bit. Thanks so much!

**Comment by maruohon** [comment]
Hmm, it seems that the `modifyOtherExplosionDropChance` functionality breaks the EFLN. Or more likely simply the fact that I'm replacing the explosion when that option is enabled, and since Tinkers likely uses a custom explosion which reports "no block damage", then the resulting explosion won't actually destroy anything...

So you can avoid this issue by disabling that option in the Environmental Creepers config for now (assuming you don't care about that option that much, only the Creepers?). I should probably add a blacklist config for explosion types that I shouldn't modify, and add the EFLN to that by default.

**Comment by TeetoKaziim** [comment]
Ah, thanks for the prompt response, and temporary fix! Yeah, mostly it's the explosions I'm not responsible for (directly) that I am worried about!

The best to you! Sorry to heap work onto your plate :D

**Comment by maruohon** [comment]
The explosion type blacklist was added a while back in version 1.12.1-1.2.1, thus resolving this issue.
